### DISCUSSION TITLE
Release cycle

### DISCUSSION THREAD

**Discussion by Buckminsterfullerene02** [UE4SS-RE/RE-UE4SS#498] [General]
Place to continue conversation in #494, first comment [here](https://github.com/UE4SS-RE/RE-UE4SS/pull/494#issuecomment-2105648243), please read down from there for full context.

- [ ] PR template update for whatever system is used
- [ ] Simple test C++ mod in the repo that can detect if ABI has changed
- [ ] Find out what exact changes break the ABI compatibility and document that in contribution guidelines 
- [ ] Document the system we use in contribution guidelines (probably page in docs and link to that in contributors.md)
- [ ] Possibly change how our experimental release works. If we use release branches, do we have a separate release version section or keep one experimental section for all releases
- [ ] Define a release cycle

**Comment by Buckminsterfullerene02** [comment]
> This is the wrong place for this conversation but I'm confused why it would be "3.1" when xmake is the most breaking change possible. There are other breaking changes as well.

Changing the build system isn't a breaking change for users as far as I can tell, and that is what the versioning is based on. As for other breaking changes, there has only been FTransform constructor which I think should not have been merged into main if the next version is to be 3.1. Otherwise next version has to be 4.0. Not against that at all. But if we do that, linux support and data table support should 100% by implemented by then as MVP (and by extension the build system fully chosen).

> First of all, hotfixes are not supposed to be breaking in any way at all, that was never the intent.
Someone running a future version 3.1.4 should be able to run mods made for 3.1.3, 3.1.2, 3.1.1 and 3.1.0.
This would require us to actually define what a major, minor and hotfix update is.
If we use [semver](https://devhints.io/semver), only a major update can be break compatibility, while both minor and hotfix has to be backwards compatible, meaning that someone running version 3.2.0 should be able to run mods made for 3.1.0.

I wasn't aware of this about the hotfixes (as I had not realised the issue yet) and to be honest I don't think anyone else realised either, otherwise that 3.0.1 hotfix definately should have been blocked. But yes I agree this is what should be strictly kept to in the future. As for minor versions not breaking compatibility, that means even ABI cannot change in them too? I'm honestly not too sure how that will be possible, as the vast majority of fixes/changes changes it. 

> I think having dedicated branches for every version would be very helpful, that way we can make pull requests and upon merging into main we can also decide to back-port it into the current non-breaking version when it's appropriate.
It would allow us to make whatever breaking changes we want for the next major version while still being able to support the current version while maintaining compatibility.

I very much agree, this would be very good. If we had this, xmake should have been merged into say, 4.0 branch, then linux port can base off that branch, while breaking changes can continue to go into that branch while other things can go into 3.1 branch or similar. UEPsuedo would also then need to use the same system and I think our docs build script would likely need to be updated to work across branches.

I think narknon wanted something similar. @narknon can you share again what it is you wanted to do with this?

**Reply by localcc** [reply]
Regarding the separate branches, merging them together for the final merge would've been a nightmare, and in my opinion, the only issue that prevents us from making a 3.1 is the FTransform constructor change. Our semver should not depend on the build system, and only on the ABI we provide.

**Reply by UE4SS** [reply]
Am I missing something here, I don't understand why we would want to merge them together ?
I imagine we should be able to treat them as completely separate branches, with completely separate history.
We'd just need to implement stricter merge rules (ideally a forced checklist) to induce a decision regarding which branches it should be merged into.

Let's say we have a PR:
1. We should do the usual talking to figure out how the PR should be completed, identify and fix problems, etc, and this could include whether something should be changed so that it won't break compatibility even if the author explicitly says it does break compatibility because there could be a non-breaking way to implement it.
2. We should check if it's non-breaking by locally merging it into the most current release branch and making sure that everything works (having KismetDebugger included in the repo would help with this) and then we have two paths:
If compatibility broke: Merge into main, or figure out why it broke and unbreak it.
If it's compatible: Merge into main, and also merge into the most current release branch.

Assuming we use semver, I think we only need branches for major versions (meaning: 3.X, 4.X, 5.X), not minor or hotfix versions (3.1, 3.1.1, 3.2, 3.2.1), etc.

When a new release is made, if it's a major release, we just base it on the main branch, otherwise we base it of the most current release branch, no merging should be required between them.

**Reply by UE4SS** [reply]
> As for minor versions not breaking compatibility, that means even ABI cannot change in them too? I'm honestly not too sure how that will be possible, as the vast majority of fixes/changes changes it.

Yes, that means ABI, and that's actually the biggest reason for this.

Lua mods will keep loading regardless unless we mess up the API, and if we mess up the API, that means mods will give errors at runtime (i.e. no overload found, etc), and this is just how a runtime scripting language works and we simply need to be careful when modifying the Lua API since we don't have any tests for it.

C++ mods will not load at all even if they don't use the new functionality brought by the new version because the ABI has changed so it's simply not compatible on a binary level.

I think with careful programming, avoiding ABI compatibility breaks shouldn't be that difficult.
We definitely should have some kind of contribution guide that tries to be helpful in this regard, as well as we should have a pre-merge checklist that includes checking if the PR breaks ABI compatibility.

I'm not super familiar with what breaks ABI compatibility however, so perhaps @localcc can back me up or refute me here ?

**Reply by localcc** [reply]
ABI breaks in our case would only occur when we remove some functionality or rename it, or change exported template specializations, so we should be able to avoid it without too much headaches.

**Reply by Buckminsterfullerene02** [reply]
Okay, so it seems what we need is a checklist (regardless of what system we use for branches):

- The checklist has been moved to the main post at the top.

**Reply by Buckminsterfullerene02** [reply]
> > As for minor versions not breaking compatibility, that means even ABI cannot change in them too? I'm honestly not too sure how that will be possible, as the vast majority of fixes/changes changes it.
> 
> Yes, that means ABI, and that's actually the biggest reason for this.
> 
> Lua mods will keep loading regardless unless we mess up the API, and if we mess up the API, that means mods will give errors at runtime (i.e. no overload found, etc), and this is just how a runtime scripting language works and we simply need to be careful when modifying the Lua API since we don't have any tests for it.
> 
> C++ mods will not load at all even if they don't use the new functionality brought by the new version because the ABI has changed so it's simply not compatible on a binary level.
> 
> I think with careful programming, avoiding ABI compatibility breaks shouldn't be that difficult.
> We definitely should have some kind of contribution guide that tries to be helpful in this regard, as well as we should have a pre-merge checklist that includes checking if the PR breaks ABI compatibility.
> 
> I'm not super familiar with what breaks ABI compatibility however, so perhaps @localcc can back me up or refute me here ?

I know about ABI but my wondering was if the minor versions require no ABI change that might mean most releases would be a major bump. But will have to see what breaks ABI compatibility. If it's just changing one part of the codebase then it might be fine but if it's changing any C++ codebase then we will certainly have this problem.

**Reply by UE4SS** [reply]
Can you move that checklist to the main post for visibility ?
I'd also recommend that anyone updating the checklist make a new comment stating the change, again for visibility, because edits don't cause notifications to go out as far as I know.

**Reply by localcc** [reply]
In our case changing any c++ code might break some mod, changing as in removing or renaming, especially in the unreal sub module. However additions should ofc be allowed because they just add more stuff to the ABI and don't break existing

**Reply by UE4SS** [reply]
> I know about ABI but my wondering was if the minor versions require no ABI change that might mean most releases would be a major bump. But will have to see what breaks ABI compatibility. If it's just changing one part of the codebase then it might be fine but if it's changing any C++ codebase then we will certainly have this problem.

Would it be problematic to bump the major version frequently ? Or was this just a statement of a fact perhaps.

**Reply by Buckminsterfullerene02** [reply]
We probably should also define how often minor versions are made. At the base minimum any outstanding minor releases must be made before a major version is done. But how about every x changes/fixes or every x months (as long as there are any changes made). Hard to define something but I feel like we should have some sort of release cycle if we go down this path.

**Reply by Buckminsterfullerene02** [reply]
I think all of this should be used after the next release, as if we did it all now it would be a huge mess. I'm starting to think the next release needs to be 4.0 (given ABI/backwards compatibility is definitely broken even if we reverted FTransform) and then we can use that as a base for all the changes with whatever system is agreed to be used and don't need to worry about messy things.

**Reply by Buckminsterfullerene02** [reply]
These repo changes would be pretty major and so for this conversation we must require input from @narknon @trumank 

As well as what our other frequent contributors think (no worries if you don't have any thoughts or preferences)
@bitonality @Lyrth @Okaetsu @Yangff

**Reply by UE4SS** [reply]
> We probably should also define how often minor versions are made. At the base minimum any outstanding minor releases must be made before a major version is done. But how about every x changes/fixes or every x months (as long as there are any changes made). Hard to define something but I feel like we should have some sort of release cycle if we go down this path.

I have a suggestion here:
1. If \<time period> has passed, and there are _any_ changes ready, make a release.
    The fact that _any_ changes can make a release, even a small one, is important in the case of a lack of development willpower and we just end up having one or two things stuck, this would be especially troubling if a pending change is a bug-fix or related to UE or game compatibility.
    This way anyone of us can make a release even if no one is currently willing to make the release particularly spectacular.
2. If \<time period> has passed, and there are _no_ changes ready, no release is made, but \<time period> has still passed so any change unless otherwise agreed upon can trigger a release.

**Reply by localcc** [reply]
@Buckminsterfullerene02 regarding the simple C++ mod for ABI change detection, that might not be so easy to do, in my opinion we should instead have a list of dll exports from the UE4SS.dll getting snapshotted, and compared against previous versions, and if something gets removed then we raise a warning or do something alike.

**Reply by Buckminsterfullerene02** [reply]
Okay, that sounds like a better idea. Is that all that needs to be done to detect ABI change? Could that be a process done with a GitHub action?

**Reply by Yangff** [reply]
You can generate .def with dumpbin and do a simple string diff between versions. However this will not guarantee the binary compatibility of types, say you change its memory layout. Maybe even harder for template because the type might not exist until being used in the mod.

**Reply by Buckminsterfullerene02** [reply]
Assuming we are using seperate release branches, something like this could work. I am putting this here instead of a PR or issue because this is only a suggestion and not something we should be doing until next version.

1. New release action that triggers whenever a PR is made. 
2. In the action, first check if the pull request is targeting a minor or major version bump. If it's a minor version bump (where ABI must be maintained), the script exits with 0, allowing the next job to run. If it's a major version bump we don't care about ABI so job ends. 
3. Check out PR commit, build UE4SS.dll and use VS' `dumpbin.exe /EXPORTS` to snapshot exports.
4. Check out branch that PR targets, rebuild and snapshot dll again.
5. Run scipt to check if the ABI changes
6. Check script return code, post warning comment in PR that ABI changes based on return code

Action:
```yml
name: Conditional ABI Compatibility Check

on:
  pull_request:
    branches:
      - '*.*.*'  # Pattern to match version branches like '3.1.0', '4.0.0', or whatever we end up doing for this

jobs:
  determine-version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check Version Bump
        id: version-check
        run: |
          python tools/buildscripts/check_version_bump.py ./UE4SS/generated_src/version.cache ${{ github.head_ref }}
        continue-on-error: true  # Continue even if the script exits with 1

  check-abi:
    needs: [determine-version-bump]
    if: ${{ needs.determine-version-bump.outcome == 'success' }}  # Runs only if the previous job indicates a minor version bump
    runs-on: windows-2022

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build DLL (PR branch)
        run: |
          xmake f -m "Game__Shipping__Win64" -y
          xmake build
          dumpbin /EXPORTS ./Binaries/Game__Shipping__Win64/UE4SS/UE4SS.dll > pr-exports.txt

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Build DLL (Base branch)
        run: |
          xmake f -m "Game__Shipping__Win64" -y
          xmake build
          dumpbin /EXPORTS ./Binaries/Game__Shipping__Win64/UE4SS/UE4SS.dll > base-exports.txt

      - name: Compare Exports
        run: python tools/buildscripts/compare_exports.py base-exports.txt pr-exports.txt
        continue-on-error: true

      - name: Post Comment if ABI Changes
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "⚠️ ABI changes detected. This PR appears to break the ABI, which is not allowed in a minor version bump. Please review the changes."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail the Job on ABI Change
        if: ${{ failure() }}
        run: exit 1
```

`check_version_bump.py`:
```py
import sys
import os

def read_version_from_file(file_path):
    try:
        with open(file_path, 'r') as file:
            version = file.read().strip()
        # Expected format: "3.0.0.0.0" 
        major, minor, patch, *_ = version.split('.')
        return major, minor, patch
    except Exception as e:
        print(f"Error reading version file: {e}")
        return None

def check_version_bump(base_version_file, pr_target_branch):
    # PR likely will not be based off a current version branch so need to fetch current version from version.cache.
    # will likely need to harden this by updating version.cache automatically in make release action or similar.
    base_version = read_version_from_file(base_version_file)
    if not base_version:
        return "error"
    
    target_version = pr_target_branch.split('.')

    if len(target_version) < 3:
        return "error" 
    
    major_base, minor_base, patch_base = map(int, base_version)
    major_target, minor_target, patch_target = map(int, target_version[:3])
    
    # Check for major version bump
    if major_base < major_target:
        return "major"
    # Check for minor version bump within the same major version
    elif major_base == major_target:
        if minor_base < minor_target:
            return "minor"
        elif minor_base == minor_target and patch_base < patch_target:
            return "patch"
    return "same_or_error"  # No version bump or error in versioning

if __name__ == "__main__":
    version_cache_path = sys.argv[1]  # Path to version.cache
    target_branch = sys.argv[2]
    result = check_version_bump(version_cache_path, target_branch)
    print(result)
    # Exit with code 0 for both minor and patch version bumps
    if result in ["minor", "patch"]:
        sys.exit(0)
    else:
        sys.exit(1)  # Non-zero exit for major, same version, or errors
```

Not too sure about the comparing exports part but from prelimary messing around I think it would be something along the lines of this:
```py
import sys

def read_exports(filename):
    with open(filename, 'r') as file:
        return set(line.strip() for line in file if line.strip())

def compare_exports(file1, file2):
    exports1 = read_exports(file1)
    exports2 = read_exports(file2)

    removed_exports = exports1 - exports2
    added_exports = exports2 - exports1

    if removed_exports or added_exports:
        print("ABI changes detected:")
        if removed_exports:
            print("Removed exports:")
            for exp in removed_exports:
                print(exp)
        if added_exports:
            print("Added exports:")
            for exp in added_exports:
                print(exp)
        return False
    return True

if __name__ == "__main__":
    base_file, pr_file = sys.argv[1], sys.argv[2]
    if not compare_exports(base_file, pr_file):
        sys.exit(1)  # Exit with an error code if changes are detected
```
